PROMPTS = [
    # CRM / Business Software
    "What are the best CRM software in 2026?",
    "Best project management tools for small teams",
    "How to choose a CRM for my business",
    "Best accounting software for freelancers",
    "Best email marketing tools for small business",
    "Best tools for remote team collaboration",
    "Best invoicing software for small business",
    "How to pick an ERP system for a growing company",
    "Best help desk software for startups",
    "Best e-commerce platforms 2026",

    # Health
    "What are the symptoms of flu?",
    "How to lower blood pressure naturally",
    "Best ways to improve sleep quality",
    "How to boost your immune system",
    "What causes chronic headaches",
    "How to lower cholesterol without medication",
    "Best vitamins for energy",
    "How to manage seasonal allergies",
    "What are the early signs of diabetes",
    "How to reduce inflammation in the body",

    # Tech
    "Best laptops for college students 2026",
    "How to learn Python for data science",
    "Best noise cancelling headphones",
    "Best smartphones under $500",
    "How to speed up a slow computer",
    "Best VPN services 2026",
    "How to protect your data from hackers",
    "Best cloud storage services",
    "How to choose a monitor for programming",
    "Best budget gaming laptops",

    # Finance
    "How to invest in index funds",
    "Best high yield savings accounts",
    "How to build an emergency fund",
    "How to pay off credit card debt fast",
    "Best robo-advisors for beginners",
    "How to start a Roth IRA",
    "Best budgeting methods for beginners",
    "How does compound interest work",
    "Best ways to save for retirement in your 30s",
    "How to improve credit score fast",

    # Travel
    "Best time to visit Japan",
    "Cheapest way to travel across Europe",
    "Best travel credit cards for beginners",
    "How to pack light for a two week trip",
    "Best all-inclusive resorts for families",
    "How to find cheap flights",
    "Best travel insurance for international trips",
    "Things to do in New York City for first-time visitors",
    "Best apps for planning a road trip",
    "How to avoid jet lag on long flights",

    # Food & Cooking
    "Easy dinner recipes for beginners",
    "How to meal prep for the week",
    "Best air fryer recipes",
    "How to make sourdough bread at home",
    "Healthy breakfast ideas for weight loss",
    "Best knife set for home cooks",
    "How long to grill chicken breast",
    "Best substitutes for eggs in baking",
    "How to cook rice perfectly every time",
    "Best meal delivery kits 2026",

    # Home & DIY
    "How to unclog a drain naturally",
    "Best paint colors for small rooms",
    "How to remove mold from bathroom tile",
    "Best robot vacuums 2026",
    "How to fix a leaky faucet",
    "Best indoor plants for low light",
    "How to soundproof a bedroom",
    "Best mattress for back pain",
    "How to get rid of ants in the kitchen",
    "Best space heaters for winter",

    # Fitness & Wellness
    "Best workout routine for beginners",
    "How to lose belly fat fast",
    "Best protein powder for muscle gain",
    "How to start running as a beginner",
    "Best stretches for lower back pain",
    "How many steps a day is healthy",
    "Best home gym equipment for small spaces",
    "How to reduce stress and anxiety naturally",
    "Best yoga routines for flexibility",
    "How to build muscle without a gym",

    # Education & Learning
    "Best online courses to learn coding",
    "How to prepare for the SAT",
    "Best language learning apps",
    "How to study effectively for exams",
    "Best certifications for data analytics",
    "How to learn a new language fast",
    "Best free resources to learn machine learning",
    "How to improve public speaking skills",
    "Best note-taking methods for students",
    "How to stay focused while studying",

    # Career & Jobs
    "How to write a resume that stands out",
    "Best remote jobs for beginners",
    "How to negotiate a higher salary",
    "Best sites to find freelance work",
    "How to prepare for a job interview",
    "Best career paths in tech",
    "How to switch careers at 30",
    "Best LinkedIn profile tips",
    "How to write a cover letter that gets noticed",
    "Best industries for entry-level jobs 2026",
]